### ISSUE TITLE
"Raw": int(fields[9]) ValueError: invalid literal for int() with base 10: '0/0'

### ISSUE THREAD

**Issue by dechamps** [cloudandheat/prometheus_smart_exporter#2]
When I attempt to run the exporter on my machine, the helper fails with:

```
ERROR:smart_exporter_helper:while handling client
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/smart_exporter_helper/__init__.py", line 249, in main
    handle_client(client_sock)
  File "/usr/local/lib/python3.6/dist-packages/smart_exporter_helper/__init__.py", line 142, in handle_client
    info = read_drive_info("/dev/"+device)
  File "/usr/local/lib/python3.6/dist-packages/smart_exporter_helper/__init__.py", line 112, in read_drive_info
    "Raw": int(fields[9]),
ValueError: invalid literal for int() with base 10: '0/0'
```

Looking at the code, I believe the issue is that for one of my drives, in the `RAW_VALUE`, the value is `0/0` for `234 Thermal_Throttle`, something that `smart_exporter_helper` doesn't seem to handle properly.

```
# smartctl -iA /dev/sdb
smartctl 6.6 2016-05-31 r4324 [x86_64-linux-4.16.0-2-amd64] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Intel 730 and DC S35x0/3610/3700 Series SSDs
Device Model:     INTEL SSDSC2BB800G4
Serial Number:    (redacted)
LU WWN Device Id: (redacted)
Firmware Version: D2010370
User Capacity:    800,166,076,416 bytes [800 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2 T13/2015-D revision 3
SATA Version is:  SATA 2.6, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Tue Jul 24 12:29:46 2018 BST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

=== START OF READ SMART DATA SECTION ===
SMART Attributes Data Structure revision number: 1
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  5 Reallocated_Sector_Ct   0x0032   100   100   000    Old_age   Always       -       0
  9 Power_On_Hours          0x0032   100   100   000    Old_age   Always       -       5254
 12 Power_Cycle_Count       0x0032   100   100   000    Old_age   Always       -       6
170 Available_Reservd_Space 0x0033   100   100   010    Pre-fail  Always       -       0
171 Program_Fail_Count      0x0032   100   100   000    Old_age   Always       -       0
172 Erase_Fail_Count        0x0032   100   100   000    Old_age   Always       -       0
174 Unsafe_Shutdown_Count   0x0032   100   100   000    Old_age   Always       -       5
175 Power_Loss_Cap_Test     0x0033   100   100   010    Pre-fail  Always       -       670 (29 9035)
183 SATA_Downshift_Count    0x0032   100   100   000    Old_age   Always       -       0
184 End-to-End_Error        0x0033   100   100   090    Pre-fail  Always       -       0
187 Reported_Uncorrect      0x0032   100   100   000    Old_age   Always       -       0
190 Temperature_Case        0x0022   066   064   000    Old_age   Always       -       34 (Min/Max 23/37)
192 Unsafe_Shutdown_Count   0x0032   100   100   000    Old_age   Always       -       5
194 Temperature_Internal    0x0022   100   100   000    Old_age   Always       -       45
197 Current_Pending_Sector  0x0032   100   100   000    Old_age   Always       -       0
199 CRC_Error_Count         0x003e   100   100   000    Old_age   Always       -       26
225 Host_Writes_32MiB       0x0032   100   100   000    Old_age   Always       -       471567
226 Workld_Media_Wear_Indic 0x0032   100   100   000    Old_age   Always       -       880
227 Workld_Host_Reads_Perc  0x0032   100   100   000    Old_age   Always       -       34
228 Workload_Minutes        0x0032   100   100   000    Old_age   Always       -       315196
232 Available_Reservd_Space 0x0033   100   100   010    Pre-fail  Always       -       0
233 Media_Wearout_Indicator 0x0032   100   100   000    Old_age   Always       -       0
234 Thermal_Throttle        0x0032   100   100   000    Old_age   Always       -       0/0
241 Host_Writes_32MiB       0x0032   100   100   000    Old_age   Always       -       471567
242 Host_Reads_32MiB        0x0032   100   100   000    Old_age   Always       -       249231
```

**Comment by 0xd3e** [comment]
Does the `smart_exporter_helper` only fail on the `RAW_VALUE` of the attribute `Thermal_Throttle`? The attributes `Power_Loss_Cap_Test ` and `Temperature_Case` also contain some non-numerical characters, so I would assume that it should fail there too.

**Comment by dechamps** [comment]
My understanding is that the code splits the columns based on whitespace, which explains why it doesn't choke on ` 670 (29 9035)` and `34 (Min/Max 23/37)`.

**Comment by dechamps** [comment]
@danieltrautmann: My understanding is that the code splits the columns based on whitespace, which explains why it doesn't choke on ` 670 (29 9035)` and `34 (Min/Max 23/37)`.

**Comment by 0xd3e** [comment]
Okay. You are right.

**Comment by dechamps** [comment]
For those encountering this issue, please apply the patch from #3 to fix. There appears to be some misunderstanding with @SPFZ which is why this has not been merged yet.
