### ISSUE TITLE
smart_exporter_helper wants int while smart sees "---" on ssd

### ISSUE THREAD

**Issue by cah-link** [cloudandheat/prometheus_smart_exporter#7]
```
/usr/bin/smart_exporter_helper[796]: ERROR:smart_exporter_helper:while handling client
                                                          Traceback (most recent call last):
                                                            File "/usr/lib/python3/dist-packages/smart_exporter_helper/__init__.py", line 249, in main
                                                              handle_client(client_sock)
                                                            File "/usr/lib/python3/dist-packages/smart_exporter_helper/__init__.py", line 142, in handle_client
                                                              info = read_drive_info("/dev/"+device)
                                                            File "/usr/lib/python3/dist-packages/smart_exporter_helper/__init__.py", line 111, in read_drive_info
                                                              "Thresh": int(fields[5]),
                                                          ValueError: invalid literal for int() with base 10: '---'

sudo smartctl -a /dev/sda
smartctl 6.5 2016-01-24 r4214 [x86_64-linux-4.15.0-34-generic] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Device Model:     SanDisk SD8SB8U512G1122
Serial Number:    170225423404
LU WWN Device Id: 5 001b44 4a6ab4778
Firmware Version: X4140000
User Capacity:    512,110,190,592 bytes [512 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        Not in smartctl database [for details use: -P showall]
ATA Version is:   ACS-2 T13/2015-D revision 3
SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Fri Oct 26 08:19:47 2018 UTC
SMART support is: Available - device has SMART capability.
SMART support is: Enabled


ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
  5 Reallocated_Sector_Ct   0x0032   100   100   ---    Old_age   Always       -       0

```

**Comment by SPFZ** [comment]
Should be solveable via a similar solution as in #3
